language: python
dist: xenial
sudo: true

python:
  - 3.7

install:
  - pip install -q -r requirements-dev.txt codecov

script:
  - flake8 ebdjango
  - pytest ebdjango --cov=ebdjango

after_success:
  - codecov
